apiVersion: v1
kind: Service
metadata:
  name: keycloakdb
spec:
  ports:
    - port: {{ .Values.keycloakdb.servicePort }}
      targetPort: {{ .Values.keycloakdb.containerPort }}
  selector:
    app: keycloakdb